[tool.poetry]
name = "iz-order-backend"
version = "0.1.0"
description = ""
authors = ["vu.pn <vu.pn@zinza.com.vn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
